# Generated by Django 6.0.6 on 2026-06-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
